server:
  port: 8086
  shutdown: graceful
  error:
    include-stacktrace: never
    include-message: never

spring:
  application:
    name: identity-service
  lifecycle:
    timeout-per-shutdown-phase: 20s

  datasource:
    url: ${IDENTITY_DB_URL:jdbc:postgresql://localhost:5434/hotelos?currentSchema=identity}
    username: ${IDENTITY_DB_USER:identity_user}
    password: ${IDENTITY_DB_PASSWORD:identity_dev_pass}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    schemas: identity
    default-schema: identity
    create-schemas: false
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: identity

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${HOTELOS_SWAGGER_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: ${HOTELOS_SWAGGER_ENABLED:true}

hotelos:
  jwt:
    private-key-path: ${HOTELOS_JWT_PRIVATE_KEY_PATH:secrets/jwt-private.pem}
    public-key-path: ${HOTELOS_JWT_PUBLIC_KEY_PATH:secrets/jwt-public.pem}
    kid: ${HOTELOS_JWT_KID:hotelos-rsa-key-1}
    issuer: ${HOTELOS_JWT_ISSUER:hotelos-identity}
    audience: ${HOTELOS_JWT_AUDIENCE:hotelos-api}
  bootstrap:
    admin:
      username: ${HOTELOS_BOOTSTRAP_ADMIN_USERNAME:}
      password: ${HOTELOS_BOOTSTRAP_ADMIN_PASSWORD:}
