server:
  port: 8083
  shutdown: graceful
  error:
    include-stacktrace: never
    include-message: never
spring:
  application:
    name: room-service
  lifecycle:
    timeout-per-shutdown-phase: 20s
  datasource:
    url: ${ROOM_SERVICE_DB_URL:jdbc:postgresql://localhost:5434/hotelos}
    username: ${ROOM_SERVICE_DB_USER:room_service_user}
    password: ${ROOM_SERVICE_DB_PASSWORD:room_service_dev_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: room_service
  flyway:
    enabled: true
    default-schema: room_service
    schemas: room_service
    create-schemas: false
    baseline-on-migrate: false
    clean-disabled: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
hotelos:
  outbox:
    poll-interval-ms: 500
    batch-size: 10
    confirm-timeout-ms: 3000
